version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=${PORT}

volumes:
  pgdata:
  redis_data:

